---
- name: Ensure yum-utils is installed
  yum:
    name: yum-utils
    state: present
  when: ansible_distribution_major_version == '7'

- name: Install available updates
  yum:
    name: "*"
    state: latest
    update_cache: true

- name: Check if a restart is required
  command:
    cmd: "needs-restarting -r"
  register: req_restart_status
  failed_when: "'FAILED' in  req_restart_status.stdout"
  changed_when: "'restart required' in req_restart_status.stdout"
  when: ansible_distribution_major_version == '7'
  
- name: Check if a restart is required
  command:
    cmd: "dnf needs-restarting -r"
  register: req_restart_status
  failed_when: "'FAILED' in  req_restart_status.stdout"
  changed_when: "'restart required' in req_restart_status.stdout"
  when: ansible_distribution_major_version == '8' or ansible_distribution == 'Fedora'

- name: Restart host if required
  reboot:
    reboot_timeout: 500
  when: "reboot and req_restart_status.rc == 1"
